config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resources :users, only: %i[new create edit update]
    resource :session, only: %i[new create destroy]

    resources :questions do
      resources :comments, only: %i[create destroy]
      resources :answers, except: %i[new show]
    end

    resources :answers, except: %i[new show] do
      resources :comments, only: %i[create destroy]
    end
    namespace :admin do
      resources :users, only: %i[index create]
    end

    root 'pages#index'
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  include Commentable

  belongs_to :user
  has_many :answers, dependent: :destroy
  validates :title, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 2 }
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  include QuestionsAnswers
  before_action :_question!, only: %i[show destroy edit update]

  def show
    load_questions_answers
  end

  def destroy
    @question.destroy
    flash[:success] = t '.success'
    redirect_to questions_path
  end

  def edit; end

  def update
    if @question.update question_params
      flash[:success] = t '.success'
      redirect_to questions_path
    else
      render :edit
    end
  end

  def index
    @questions = Question.order(created_at: :desc).page(params[:page])
    @questions = @questions.decorate
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.build(question_params)
    if @question.save
      flash[:success] = t '.success'
      redirect_to questions_path
    else
      render :new
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def _question!
    @question ||= Question.find(params[:id])
  end
end

app/views/questions/_form.html.erb
<%= render 'shared/errors', object: @question %>

<%= form_with model: @question do |f| %>
<div class="mb-3 row">
  <div class='col-sm-2 col-form-label'>
    <%= f.label :title %>
  </div>
  <div class="col-sm-10">
    <%= f.text_field :title, placeholder: "Title", class: 'form-control' %>
  </div>
</div>
<div class="mb-3 row">
  <div class='col-sm-2 col-form-label'>
    <%= f.label :body %>
  </div>
  <div class="col-am-10">
    <%= f.text_area :body, placeholder: "Body", class: 'form-control' %>
  </div>
</div>
<%= f.submit t('global.button.submit'), class: 'btn btn-primary' %>
<% end %>

app/views/questions/_question.html.erb
<article class="card m-3">
  <section class="card-header">
    <%= question.user.gravatar %>
    <%= question.user.name_or_email %>
  </section>
  <div class="card-body">
    <h2><%= question.title %></h2>
    <section class="card-text">
      <time datetime="<%= question.formatted_created_at %>">
        <%= question.formatted_created_at %>
      </time>
      <p class="my-2">
        <%= truncate strip_tags(question.body), length: 150, omission: t('global.text.omission') %>
      </p>
    </section>
    <%= link_to t('global.button.show'), question_path(question), class: 'btn btn-primary' %>
    <%= link_to t('global.button.edit'), edit_question_path(question), class: 'btn btn-secondary' %>
    <%= link_to t('global.button.delete'), question_path(question), data: {method: :delete,   confirm:'Are you sure?'}, class: 'btn btn-danger' %>
  </div>
</article>

app/views/questions/edit.html.erb
<% provide :page_title, t('.title') %>
<% currently_at t('menu.questions') %>

<h1 class="mb-4"><%= t '.title' %></h1>

<%= render "form" %>

app/views/questions/index.html.erb
<% provide :page_title, t('.title') %>
<% currently_at t('menu.questions') %>

<h1 class="mb-4"><%= t('.title') %></h1>

<%= link_to t('.new'), new_question_path, class: 'btn btn-primary btn-lg mb-4' %>
<%= paginate @questions %>

<%= render @questions %>

<%= paginate @questions %>

app/views/questions/new.html.erb
<% provide :page_title, t('.title') %>
<% currently_at t('menu.questions') %>

<h1 class="mb-4"><%= t('.title') %></h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<% provide :page_title, @question.title %>
<% currently_at t('menu.questions') %>

<h1 class="mb-4"><%= @question.title %></h1>

<time datetime="<%= @question.formatted_created_at %>">
  <%= @question.formatted_created_at %>
</time>
<div  class="lead my-4">
  <%= sanitize  @question.body %>
</div>

<div class="mb-3">
  <%= @question.user.gravatar %>
  <%= @question.user.name_or_email %>
</div>

<%= render 'comments/commentable', commentable: @question, comment: @comment,
  html_id: 'questionComments' %>

<div class="border-top border-bottom py-3 mt-3">
  <div class="btn-group">
    <%= link_to t('global.button.show'), question_path(@question), class: 'btn btn-primary' %>
    <%= link_to t('global.button.edit'), edit_question_path(@question), class: 'btn     btn-secondary' %>
    <%= link_to t('global.button.delete'), question_path(@question), data: {method: :delete,   confirm: 'Are you sure?'}, class: 'btn btn-danger' %>
  </div>
</div>

<hr>

<h2 class='m-3'><%= t('.write_answer') %></h2>
<%= render 'answers/form', object: @answer %>

<h2 class='m-3'><%= t('.answers') %></h2>
<%= paginate @answers %>
<%= render partial: 'answers/answer', collection: @answers, as: :answer, locals: {question: @question} %>
<%= paginate @answers %>